osx_image: xcode8
language: objective-c
podfile: Example/Podfile
script: xcodebuild -workspace Example/RCActionView.xcworkspace -scheme RCActionView-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' | xcpretty -c && exit ${PIPESTATUS[0]} 
notifications:
  email: false
